// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "player":return img`
..............................
..............................
.......ffffff.................
.......ffffff.................
.......eeffee.................
.......eeffee.................
.......ffffff.................
.......ffffff.................
.........ff...................
.........ff...................
.....ffffffffff...............
.....ffffffffff...............
.........ff...................
.........ff...................
.........ff...................
.........ff...................
.......ffffff.................
.......ffffff.................
.....ffff..ffff...............
.....ffff..ffff...............
...ffff......ffff.............
...ffff......ffff.............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
